# Generated by Django 3.1.7 on 2021-03-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='mute_notifications',
        ),
    ]
